---

application_name: dispatch-service

application_configmap: dispatch-service

postgresql_template: "{{ resources_dir }}/postgresql-persistent-template.yaml"
postgresql_service_name: dispatch-service-postgresql
postgresql_init_configmap: "{{ postgresql_service_name }}-init"
postgresql_username: jboss
postgresql_password: jboss
postgresql_database: rhpam
postgresql_max_connections: 100
postgresql_max_prepared_transactions: 100

install_enmasse_truststore_secret: true
enmasse_truststore_secret: enmasse-truststore
enmasse_truststore: enmasse.jks

postgresql_host: "{{ postgresql_service_name }}"

narayana_dbcp_max_total: 20

amqp_host: messaging.{{ project_enmasse }}.svc.cluster.local
amqp_port: 5671
amqp_query: transport.trustAll=false&transport.verifyHost=true
amqp_username: user
amqp_password: password
amqp_jms_pool_enabled: true
amqp_jms_pool_explicit_producer_cache_size: 10
amqp_jms_pool_use_anonymous_producers: false

spring_jms_pub_sub_domain: true
spring_jms_transacted: true
spring_jms_subscription_shared: true
spring_jms_subscription_durable: true
spring_jms_listener_concurrency: 20
spring_jms_listener_max_concurrency: 20

listener_destination_ride_event: topic-ride-event
listener_subscription_ride_event: dispatch-ride

listener_destination_driver_event: topic-driver-event
listener_subscription_driver_event: dispatch-driver

listener_destination_passenger_event: topic-passenger-event
listener_subscription_passenger_canceled: dispatch-passenger

send_destination_driver_command: topic-driver-command

send_destination_passenger_command: topic-passenger-command

dispatch_assign_driver_expire_duration: 5M

quartz_clustered: true

ocp_application_template: "{{ resources_dir }}/dispatch-service-template.yaml"
ocp_binary_build_config_template: "{{ resources_dir }}/dispatch-service-binary.yaml"
ocp_pipeline_build_config_template: "{{ resources_dir }}/dispatch-service-pipeline.yaml"
ocp_application_name: dispatch-service
ocp_deployment_config: dispatch-service
ocp_binary_build_config: "{{ ocp_application_name }}-binary"
ocp_pipeline_build_config: "{{ ocp_application_name }}-pipeline"
ocp_build_imagestream: redhat-openjdk18-openshift:1.4
git_url: "gogs:3000"
git_repository: "acme/dispatch-service"