DROP TABLE IF EXISTS TAXSMAPPING;
CREATE TABLE IF NOT EXISTS TAXSMAPPING(
  orderunit VARCHAR (30) PRIMARY KEY NOT NULL,
  tax1 DOUBLE,
  tax2 DOUBLE,
  tax3 DOUBLE,
  tax4 DOUBLE,
  tax5 DOUBLE
);

INSERT INTO TAXSMAPPING VALUES('ROLL', 54.7, 1.1, 2.2, 3.3, 4.4);
INSERT INTO TAXSMAPPING VALUES('BOX', 26.6, 1.1, 2.2, 3.3, 4.4);