= Cookbook Docspace

== 3 Steps to Contribute

*Step.1* clone

[source, bash]
----
git clone git@github.com:<YOUR_ID>/docs.git
----

*Step.2* Do some edit

Use any text editor to edit the adoc files, http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference] can help you in AsciiDoc Syntax.

*Step.3* Summit your change

Once your change be merged the content will show on page.

== Test locally

You may need test locally, to make sure the changes are correct, to do this install https://github.com/GitbookIO/gitbook[gitbook], then execute the following commands from the checkout location:

[source, bash]
----
$ gitbook install
$ gitbook serve -w
----

Once above commands executes successfully, the http format document can be test locally via http://localhost:4000/[http://localhost:4000/].

== Generate html/pdf/epub/mobi

You may locally create rendered forms of the documentation. To do this install https://github.com/GitbookIO/gitbook[gitbook] and https://github.com/GitbookIO/gitbook-convert[gitbook-convert], then execute the following commands from the checkout location:

[source, bash]
----
$ gitbook build ./ cookbook
$ gitbook pdf ./ cookbook.pdf
$ gitbook epub ./ cookbook.epub
$ gitbook mobi ./ cookbook.mobi
----

Once above commands executes successfully, the `cookbook` folder, `cookbook.pdf`, `cookbook.epub`, and `cookbook.mobi` will be generated.

== Changes

|===
|版本 |时间 |Notes

|1.4
|2018-11-08
|Zabbix 安装文档

|1.3
|2018-10-23
|OCP 安装文档更新到 OCP 3.11，增加用例页

|1.2
|2018-10-14
|敏捷集成

|1.1
|2018-09-13
|微服务及红帽多产品集成实践

|1.0
|2018-08-27
|基本 OpenShift 安装(3.10.14)，基本 Linux 基础，APPDEV 相关内容

|===
