---

- name: ensure user has cluster admin access
  shell: "{{ openshift_cli }} auth can-i create clusterroles"
  register: is_admin
  ignore_errors: True

- name: create cluster wide roles used by keycloak-controller
  shell: "{{ openshift_cli }} apply -n {{ ocp_project }} -f {{ resources_dir }}/cluster-roles/openshift/keycloak-controller.yaml"
  when: is_admin.stdout == "yes"

- name: Give user lookup permissions for the keycloak controller
  shell: "{{ openshift_cli }} adm policy add-cluster-role-to-user enmasse.io:keycloak-controller system:serviceaccount:{{ ocp_project }}:enmasse-admin"
  when: is_admin.stdout == "yes"

- name: check if standard-authservice service controller exists
  shell: "{{ openshift_cli }} get deployment {{ standard_authservice_deployment_name }} -n {{ ocp_project }}"
  register: standard_authservice_deployment_deployed
  ignore_errors: true
  changed_when: false

- name: deploy standard-authservice controller
  shell: "{{ openshift_cli }} apply -f {{ resources_dir }}/standard-authservice/controller-deployment.yaml -n {{ ocp_project }}"
  when: standard_authservice_deployment_deployed is failed
