---

# create project
- name: check if project {{ ocp_project }} exists
  shell: "{{ openshift_cli }} get project {{ ocp_project }}"
  register: project_result
  ignore_errors: true
  changed_when: false

- name: create project {{ ocp_project }}
  shell: "{{ openshift_cli }} new-project {{ ocp_project }} --display-name='{{ ocp_project_display_name }}' --description='{{ ocp_project_desc }}'"
  when: project_result is failed

- name: assign user {{ project_admin }} as project admin in {{ ocp_project }}
  shell: "{{ openshift_cli }} adm policy add-role-to-user admin {{ project_admin }} -n {{ ocp_project }}"
  ignore_errors: true
  when: >
    project_result is failed and
    project_admin is defined and
    project_admin is not none and
    project_admin|trim() != ""

- name: annotate project {{ ocp_project }}
  shell: "{{ openshift_cli }} annotate --overwrite namespace {{ ocp_project }} {{ project_annotations }}"
  ignore_errors: true
  when: >
    project_result is failed and
    project_annotations is defined and
    project_annotations is not none and
    project_annotations|trim() != ""

- name: give serviceaccount permissions in project {{ ocp_project }}
  shell: "{{ openshift_cli }} adm policy add-role-to-user {{ ocp_privileges }} system:serviceaccount:{{ ocp_project }}:{{ ocp_service_account }} -n {{ ocp_project}}"
  ignore_errors: true
  when: >
    project_result is failed and
    ocp_service_account is defined and
    ocp_service_account is not none and
    ocp_service_account|trim() != "" and
    ocp_privileges is defined and
    ocp_privileges is not none and
    ocp_privileges|trim() != ""
