---

- name: check if {{ configmap_name }} configmap exists
  shell: "{{ openshift_cli }} get configmap {{ configmap_name }} -n {{ ocp_project }}"
  register: configmap_exists
  ignore_errors: true
  changed_when: false

- name: copy {{ configmap_name }} configmap from template
  template: src={{item}} dest={{ playbook_work_dir }}/{{ item }}
  with_items:
    - "{{ configmap_template }}"
  when: configmap_exists is failed

- name: create {{ configmap_name }} configmap
  shell: |
     {{ openshift_cli }} create configmap {{ configmap_name }} --from-file={{ playbook_work_dir }}/{{ configmap_template }} -n {{ ocp_project }}
  when: configmap_exists is failed   