---

authentication_services:
  - none

address_controller_secret_name: address-controller-cert

resource_definitions_template: "{{ resources_dir }}/resource-definitions/resource-definitions.yaml"
brokered_address_space_plans_template: "{{ resources_dir }}/plans/brokered-plans.yaml"
standard_address_space_plans_template: "{{ resources_dir }}/plans/standard-plans.yaml"

none_authservice_secret_name: none-authservice-cert

standard_authservice_secret_name: standard-authservice-cert
standard_authservice_keycloak_admin_username: admin
standard_authservice_keycloak_admin_password: admin

enmasse_template: "{{ resources_dir }}/templates/enmasse.yaml"

enmasse_keycloak_client: enmasse-keycloak-client.jar

keycloak_deployment: keycloak

address_space_controller_enable_rbac: false
address_space_controller_enmasse_environment: development

create_address_space: true
address_space_namespace: "{{ ocp-project }}"
# brokered,standard
address_space_type: brokered
# none,standard
address_space_auth_type: none
address_space_name: "{{ address_space_type }}-default"
address_space_plan: unlimited-{{ address_space_type }}

create_external_messaging_certificate: true
external_messaging_secret_name: external-certs-messaging

# Example: [{"name":"user1","password":"user"},{"name":"user2","password":"user"}]
address_space_users: [{ name: user, password: password}]

create_address: true
# Example: [{"name":"queue1","type":"queue","plan":"standard"},{"name":"queue2","type":"queue","plan":"standard"}]
# Type: queue, topic, anycast, multicast
# Plan: unlimited, inmemory, persisted, pooled-inmemory, pooled-persisted 
address_names: >
  [{"name": "topic-driver-command", "type": "topic", "plan": "brokered-topic"},
   {"name": "topic-driver-event", "type": "topic", "plan": "brokered-topic"},
   {"name": "topic-passenger-command", "type": "topic", "plan": "brokered-topic"},
   {"name": "topic-passenger-event", "type": "topic", "plan": "brokered-topic"},
   {"name": "topic-ride-event", "type": "topic", "plan": "brokered-topic"}]
