---

# address space plans
- name: check if brokered address space plan exists
  shell: "{{ openshift_cli }} get configmap address-space-plan-brokered -n {{ ocp_project }}"
  register: brokered_address_space_plan_exists
  ignore_errors: true
  changed_when: false

- name: create brokered address space plan
  shell: "{{ openshift_cli }} apply -f {{ brokered_address_space_plans_template }} -n {{ ocp_project }}"
  when: brokered_address_space_plan_exists is failed