= 安装
:toc: manual

== Inventory

Ansible inventory 文件描述了有关集群中主机的详细信息以及 OpenShift 安装过程的详细配置。OpenShift 安装 playbooks 会读取该 inventory 文件，以了解在何处以及如何在一组主机上安装 OpenShift。 

本部分说明如何在 Master 节点编辑 `/etc/ansible/hosts`，主要通过变量控制安装。

=== 集群变量

|===
|名称 |作用域 |描述

|ansible_ssh_user
|General
|Ansible SSH 登录用户，默认 `root`，且需要免密登录。

|debug_level
|General
|Ansible 输出日志级别，可能的值 0, 2, 4, 6, 8，默认 2，输出 INFO 日志，4 为 DEBUG 日志

|openshift_clock_enabled
|General
|是否开启网络时钟 NTP，默认值 `true`

|openshift_master_cluster_method
|General
|部署多个 Master 时定义 HA 的方法，支持 `native` 方法

|openshift_master_identity_providers
|General
|配置认证提供者，

|openshift_hosted_registry_cert_expire_days
|General
|默认自动生成的证书过期时间

|os_firewall_use_firewalld
|General
|3.9 及以后的版本安装推荐使用 firewalld，设定为 `true` 默认使用 firewalld，而不是直接使用 iptables。

|openshift_router_selector
|General
|设定部署 router Pod 的节点

|openshift_registry_selector
|General
|设定部署 Registry Pod 的节点

|openshift_template_service_broker_namespaces
|General
|Enables the template service broker by specifying one or more namespaces whose templates will be served by the broker.

|openshift_master_bootstrap_auto_approve
|General
|Enables TLS bootstrapping auto approval, which allows nodes to automatically join the cluster when provided a bootstrap credential. 默认值为 `false`。

|template_service_broker_selector
|General
|设定部署 Service Broker Pod 的节点

|osm_default_node_selector
|General
|设定默认应用 Pod 部署的计算节点

|openshift_docker_insecure_registries
|General
|设定一个非安全 Docker 仓库，Ansible 运行会将其配置到 Docker。

|openshift_image_tag
|General
|设定一个全局镜像 TAG

|openshift_pkg_version
|General
|设定一个全局的 RPM 包版本号

|openshift_master_default_subdomain
|Networking
|设定路由使用的子域名地址

|os_sdn_network_plugin_name
|Networking
|设定默认网络插件名称，默认 `redhat/openshift-ovs-subnet`

|osm_cluster_network_cidr
|Networking
|This variable overrides the SDN cluster network CIDR block. This is the network from which pod IPs are assigned. Specify a private block that does not conflict with existing network blocks in your infrastructure to which pods, nodes, or the master might require access.

|openshift_portal_net
|Networking
|配置子网的范围，默认 `172.30.0.0/16`

|openshift_use_openshift_sdn
|Networking
|设定为 `false` 使 OpenShift SDN 插件失效
|===

[source, bash]
.*示例 - 全局集群变量*
----
ansible_ssh_user=root
debug_level=2
openshift_clock_enabled=true
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

openshift_hosted_registry_cert_expire_days=3650
os_firewall_use_firewalld=true

openshift_router_selector='node-role.kubernetes.io/infra=true'
openshift_registry_selector='node-role.kubernetes.io/infra=true'
template_service_broker_selector='node-role.kubernetes.io/infra=true'
osm_default_node_selector='node-role.kubernetes.io/compute=true'

openshift_template_service_broker_namespaces=['openshift','tsb']

openshift_docker_insecure_registries="registry.example.com"

openshift_metrics_hawkular_hostname=hawkular-metrics.apps.example.com

openshift_image_tag=v3.11.16
----

[source, bash]
.*示例 - 网络变量*
----
openshift_master_default_subdomain=apps.example.com

os_sdn_network_plugin_name='redhat/openshift-ovs-subnet'
#os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
#os_sdn_network_plugin_name='redhat/openshift-ovs-networkpolicy'

osm_cluster_network_cidr=10.244.0.0/16
openshift_portal_net=172.30.0.0/16
----

=== 部署类型

[source, bash]
.*确保部署类型为 openshift-enterprise*
----
openshift_deployment_type=openshift-enterprise
----

=== HOST 主机变量

[source, bash]
.*2 - Web Console 控制*
----
openshift_web_console_install=true
openshift_web_console_prefix=registry.example.com/openshift3/ose-
openshift_web_console_version=v3.10.14
----

[source, bash]
.*4 - 安装 Standalone Registry，忽略 WebConsole 等其它*
----
deployment_subtype=registry
----

=== 示例

|===
|Inventory | 说明

|link:hosts/hosts-3.11.16[hosts-3.11.16]
|OpenShift 3.11.16

|link:hosts/hosts-3.10.45[hosts-3.10.45]
|OpenShift 3.10.45

|link:hosts/hosts-3.10.14[hosts-3.10.14]
|OpenShift 3.10.14

|link:hosts/hosts-3.9.30[hosts-3.9.30]
|OpenShift 3.9.30

|link:hosts/hosts-3.9.25[hosts-3.9.25]
|OpenShift 3.9.25

|link:hosts/hosts-3.9.14[hosts-3.9.14]
|OpenShift 3.9.14

|link:hosts/hosts-3.6[hosts-3.6]
|OpenShift 3.6
|===


== 安装

[source, text]
.*1. Master 上执行 prerequisites 验证*
----
# ansible-playbook -i hosts-3.11.16 /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
----

[source, text]
.*2. Master 上执行 ansible 脚本*
----
# ansible-playbook -i hosts-3.11.16 /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml
----

== 安装成功验证

[source, text]
.*1 - 查看 INSTALLER STATUS（ansible 脚本运行的结尾）*
----
INSTALLER STATUS *****************************************************************************************************************************************************************************
Initialization              : Complete (0:00:27)
Health Check                : Complete (0:00:03)
Node Bootstrap Preparation  : Complete (0:11:25)
etcd Install                : Complete (0:00:42)
NFS Install                 : Complete (0:00:09)
Master Install              : Complete (0:03:43)
Master Additional Install   : Complete (0:01:02)
Node Join                   : Complete (0:03:48)
Hosted Install              : Complete (0:00:58)
Web Console Install         : Complete (0:00:41)
Metrics Install             : Complete (0:02:03)
Prometheus Install          : Complete (0:01:10)
Service Catalog Install     : Complete (0:07:20)
----

[source, text]
.*2 - 查看所有 Nodes*
----
# oc get nodes
NAME                 STATUS    ROLES     AGE       VERSION
infra.example.com    Ready     infra     1h        v1.10.0+b81c8f8
master.example.com   Ready     master    1h        v1.10.0+b81c8f8
node1.example.com    Ready     compute   1h        v1.10.0+b81c8f8
----

[source, text]
.*3 - 查看所有 Pods*
----
# oc get pods --all-namespaces -o wide | grep master.example.com
default                             registry-console-1-bgcqm                1/1       Running     0          1h        10.244.0.3        master.example.com
kube-service-catalog                apiserver-t4f2m                         1/1       Running     0          1h        10.244.0.7        master.example.com
kube-service-catalog                controller-manager-bswhl                1/1       Running     0          1h        10.244.0.8        master.example.com
kube-system                         master-api-master.example.com           1/1       Running     0          1h        192.168.122.101   master.example.com
kube-system                         master-controllers-master.example.com   1/1       Running     0          1h        192.168.122.101   master.example.com
kube-system                         master-etcd-master.example.com          1/1       Running     0          1h        192.168.122.101   master.example.com
openshift-infra                     hawkular-metrics-hszwd                  1/1       Running     0          1h        10.244.0.6        master.example.com
openshift-metrics                   prometheus-node-exporter-wxzjr          1/1       Running     0          1h        192.168.122.101   master.example.com
openshift-node                      sync-4mll5                              1/1       Running     0          1h        192.168.122.101   master.example.com
openshift-sdn                       ovs-cdq28                               1/1       Running     0          1h        192.168.122.101   master.example.com
openshift-sdn                       sdn-sssfl                               1/1       Running     0          1h        192.168.122.101   master.example.com
openshift-template-service-broker   apiserver-qkqvc                         1/1       Running     0          1h        10.244.0.9        master.example.com
openshift-web-console               webconsole-7c484b9ff8-76rh5             1/1       Running     1          1h        10.244.0.4        master.example.com

# oc get pods --all-namespaces -o wide | grep node1.example.com
openshift-infra                     heapster-6wxj2                          1/1       Running     0          1h        10.244.4.3        node1.example.com
openshift-metrics                   prometheus-node-exporter-lmsxz          1/1       Running     0          1h        192.168.122.105   node1.example.com
openshift-node                      sync-xzxxv                              1/1       Running     0          1h        192.168.122.105   node1.example.com
openshift-sdn                       ovs-grrvm                               1/1       Running     0          1h        192.168.122.105   node1.example.com
openshift-sdn                       sdn-fbm27                               1/1       Running     0          1h        192.168.122.105   node1.example.com

# oc get pods --all-namespaces -o wide | grep infra.example.com
default                             docker-registry-1-77krn                 1/1       Running     0          1h        10.244.2.4        infra.example.com
default                             router-1-x9q6x                          1/1       Running     0          1h        192.168.122.102   infra.example.com
openshift-ansible-service-broker    asb-1-wbbhr                             1/1       Running     0          1h        10.244.2.8        infra.example.com
openshift-infra                     hawkular-cassandra-1-ggwxr              1/1       Running     0          1h        10.244.2.6        infra.example.com
openshift-infra                     hawkular-metrics-schema-5699f           0/1       Completed   0          1h        10.244.2.5        infra.example.com
openshift-metrics                   prometheus-node-exporter-j7lr5          1/1       Running     0          1h        192.168.122.102   infra.example.com
openshift-node                      sync-qs9x2                              1/1       Running     0          1h        192.168.122.102   infra.example.com
openshift-sdn                       ovs-ghqhn                               1/1       Running     0          1h        192.168.122.102   infra.example.com
openshift-sdn                       sdn-fnl8v                               1/1       Running     0          1h        192.168.122.102   infra.example.com
----

[source, text]
.*4 - 查看不同类型节点的镜像*
----
# for i in master infra node1 ; do ssh $i.example.com 'docker images ; echo' ; done
REPOSITORY                                                    TAG                 IMAGE ID            CREATED             SIZE
registry.example.com/openshift3/ose-node                      v3.10.14            da5c8c13b7e8        11 days ago         1.27 GB
registry.example.com/openshift3/registry-console              v3.10.14            8d51f41d6fa3        13 days ago         231 MB
registry.example.com/openshift3/ose-deployer                  v3.10.14            414fcb4f3482        13 days ago         789 MB
registry.example.com/openshift3/ose-web-console               v3.10.14            e3d8bd0ed7d1        13 days ago         318 MB
registry.example.com/openshift3/ose-control-plane             v3.10.14            64b4a2f9caae        13 days ago         789 MB
registry.example.com/openshift3/ose-service-catalog           v3.10.14            96ce9ced41cd        13 days ago         312 MB
registry.example.com/openshift3/prometheus-node-exporter      v3.10.14            0a9d568fce09        13 days ago         223 MB
registry.example.com/openshift3/metrics-hawkular-metrics      v3.10.14            ac44e9cebacf        13 days ago         1.71 GB
registry.example.com/openshift3/ose-template-service-broker   v3.10.14            669fe6121623        13 days ago         283 MB
registry.example.com/openshift3/ose-pod                       v3.10.14            ddeb851f17ad        13 days ago         214 MB
registry.example.com/rhel7/etcd                               3.2.22              98217b7c8905        2 weeks ago         256 MB

REPOSITORY                                                   TAG                 IMAGE ID            CREATED             SIZE
registry.example.com/openshift3/ose-node                     v3.10.14            da5c8c13b7e8        11 days ago         1.27 GB
registry.example.com/openshift3/ose-haproxy-router           v3.10.14            b0bd92d8865b        13 days ago         808 MB
registry.example.com/openshift3/ose-deployer                 v3.10.14            414fcb4f3482        13 days ago         789 MB
registry.example.com/openshift3/ose-docker-registry          v3.10.14            a21f6776105b        13 days ago         283 MB
registry.example.com/openshift3/prometheus-node-exporter     v3.10.14            0a9d568fce09        13 days ago         223 MB
registry.example.com/openshift3/metrics-cassandra            v3.10.14            ac838937235a        13 days ago         555 MB
registry.example.com/openshift3/metrics-schema-installer     v3.10.14            c973002f575e        13 days ago         841 MB
registry.example.com/openshift3/ose-ansible-service-broker   v3.10.14            b6b9a4fb59c0        13 days ago         440 MB
registry.example.com/openshift3/ose-pod                      v3.10.14            ddeb851f17ad        13 days ago         214 MB

REPOSITORY                                                 TAG                 IMAGE ID            CREATED             SIZE
registry.example.com/openshift3/ose-node                   v3.10.14            da5c8c13b7e8        11 days ago         1.27 GB
registry.example.com/openshift3/prometheus-node-exporter   v3.10.14            0a9d568fce09        13 days ago         223 MB
registry.example.com/openshift3/metrics-heapster           v3.10.14            b43f9c9ba0c9        13 days ago         281 MB
registry.example.com/openshift3/ose-pod                    v3.10.14            ddeb851f17ad        13 days ago         214 MB
----

[source, text]
.*5 - 查看 Master 监听端口*
----
# netstat -antulop | grep LISTEN
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      12700/openshift      off (0.00/0/0)
tcp        0      0 0.0.0.0:8444            0.0.0.0:*               LISTEN      12650/openshift      off (0.00/0/0)
tcp        0      0 192.168.122.101:2379    0.0.0.0:*               LISTEN      12680/etcd           off (0.00/0/0)
tcp        0      0 192.168.122.101:2380    0.0.0.0:*               LISTEN      12680/etcd           off (0.00/0/0)
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      26356/rpcbind        off (0.00/0/0)
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      20501/openshift      off (0.00/0/0)
tcp        0      0 10.244.0.1:53           0.0.0.0:*               LISTEN      21745/dnsmasq        off (0.00/0/0)
tcp        0      0 0.0.0.0:8053            0.0.0.0:*               LISTEN      12700/openshift      off (0.00/0/0)
tcp        0      0 192.168.122.101:53      0.0.0.0:*               LISTEN      21745/dnsmasq        off (0.00/0/0)
tcp        0      0 172.17.0.1:53           0.0.0.0:*               LISTEN      21745/dnsmasq        off (0.00/0/0)
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      992/sshd             off (0.00/0/0)
tcp        0      0 127.0.0.1:11256         0.0.0.0:*               LISTEN      20501/openshift      off (0.00/0/0)
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1382/master          off (0.00/0/0)
tcp6       0      0 :::9090                 :::*                    LISTEN      1/systemd            off (0.00/0/0)
tcp6       0      0 :::10250                :::*                    LISTEN      24344/hyperkube      off (0.00/0/0)
tcp6       0      0 :::9100                 :::*                    LISTEN      21015/node_exporter  off (0.00/0/0)
tcp6       0      0 :::111                  :::*                    LISTEN      26356/rpcbind        off (0.00/0/0)
tcp6       0      0 :::10256                :::*                    LISTEN      20501/openshift      off (0.00/0/0)
tcp6       0      0 fe80::e4ec:eeff:feec:53 :::*                    LISTEN      21745/dnsmasq        off (0.00/0/0)
tcp6       0      0 fe80::bca3:6ff:fe69::53 :::*                    LISTEN      21745/dnsmasq        off (0.00/0/0)
tcp6       0      0 fe80::7cae:5cff:fe6d:53 :::*                    LISTEN      21745/dnsmasq        off (0.00/0/0)
tcp6       0      0 fe80::d0d2:cdff:fe20:53 :::*                    LISTEN      21745/dnsmasq        off (0.00/0/0)
tcp6       0      0 fe80::a018:1bff:fe00:53 :::*                    LISTEN      21745/dnsmasq        off (0.00/0/0)
tcp6       0      0 fe80::b8bd:20ff:feb6:53 :::*                    LISTEN      21745/dnsmasq        off (0.00/0/0)
tcp6       0      0 fe80::746a:65ff:fe41:53 :::*                    LISTEN      21745/dnsmasq        off (0.00/0/0)
tcp6       0      0 fe80::88e8:5ff:fecb::53 :::*                    LISTEN      21745/dnsmasq        off (0.00/0/0)
tcp6       0      0 fe80::5054:ff:fe4c:2:53 :::*                    LISTEN      21745/dnsmasq        off (0.00/0/0)
tcp6       0      0 :::22                   :::*                    LISTEN      992/sshd             off (0.00/0/0)
tcp6       0      0 ::1:25                  :::*                    LISTEN      1382/master          off (0.00/0/0)
----


