---

# create address
- name: check if address configmap exists
  shell: "{{ openshift_cli}} get configmap {{ outer_item.name }} -n {{ ocp_project }}"
  register: address_exists
  ignore_errors: true
  changed_when: false

- name: create address
  shell: |
    {{ openshift_cli}} process -f {{ resources_dir }}/templates/address.yaml \
    -p NAME={{ outer_item.name }} \
    -p NAMESPACE={{ ocp_project }} \
    -p ADDRESS_SPACE={{ address_space_name }} \
    -p ADDRESS={{ outer_item.name }} \
    -p TYPE={{ outer_item.type }} \
    -p PLAN={{ outer_item.plan }} \
    | oc apply -n {{ ocp_project }} -f -
  when: address_exists is failed