apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curl
  name: curl
  namespace: test001
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 3600
    image: kylinsoong/busybox-curl:latest
    name: curl
    resources: {}
