---

- name: check if standard address space plan exists
  shell: "{{ openshift_cli }} get configmap address-space-plan-standard -n {{ ocp_project }}"
  register: standard_address_space_plan_exists
  ignore_errors: true
  changed_when: false

- name: create standard address space plan
  shell: "{{ openshift_cli }} apply -f {{ standard_address_space_plans_template }} -n {{ ocp_project }}"
  when: standard_address_space_plan_exists is failed