---

# deploy standard authservice
- name: check if standard-authservice service exists
  shell: "{{ openshift_cli }} get service {{ standard_authservice_service_name }} -n {{ ocp_project }}"
  register: standard_authservice_service_deployed
  ignore_errors: true
  changed_when: false

- name: deploy standard-authservice service
  shell: "{{ openshift_cli }} apply -f {{ resources_dir }}/standard-authservice/service.yaml -n {{ ocp_project }}"
  when: standard_authservice_service_deployed is failed

- name: check if standard-authservice deployment exists
  shell: "{{ openshift_cli }} get deployment {{ keycloak_deployment_name }} -n {{ ocp_project }}"
  register: keycloak_deployment_deployed
  ignore_errors: true
  changed_when: false

- name: deploy standard-authservice deployment
  shell: "{{ openshift_cli }} apply -f {{ resources_dir }}/standard-authservice/keycloak-deployment.yaml -n {{ ocp_project }}"
  when: keycloak_deployment_deployed is failed

- name: check if standard-authservice persistent volume claim exists
  shell: "{{ openshift_cli }} get pvc {{ standard_authservice_pvc_name }} -n {{ ocp_project }}"
  register: standard_authservice_pvc_deployed
  ignore_errors: true
  changed_when: false

- name: deploy standard-authservice persistent volume claim
  shell: "{{ openshift_cli }} apply -f {{ resources_dir }}/standard-authservice/pvc.yaml -n {{ ocp_project }}"
  when: standard_authservice_pvc_deployed is failed

- name: check if standard-authservice route exists
  shell: "{{ openshift_cli }} get pvc {{ standard_authservice_route_name }} -n {{ ocp_project }}"
  register: standard_authservice_route_deployed
  ignore_errors: true
  changed_when: false

- name: deploy standard-authservice route
  shell: "{{ openshift_cli }} apply -f {{ resources_dir }}/standard-authservice/route.yaml -n {{ ocp_project }}"
  when: standard_authservice_route_deployed is failed