---

- name: create test route
  shell: "{{ openshift_cli }} create route edge testroute --service=testsvc --port=80 -n {{ ocp_project }}"

- name: get domain url
  shell: echo $({{ openshift_cli }} get route testroute -o jsonpath='{.spec.host}' -n {{ ocp_project }} | sed "s/testroute-{{ ocp_project }}.//g")
  register: ocp_domain_host

- name: delete test route
  shell: "{{ openshift_cli }} delete route testroute -n {{ ocp_project }}"

- name: set ocp_domain fact
  set_fact: 
    ocp_domain: "{{ ocp_domain_host.stdout }}"