apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app-svc-clusterip
  namespace: test001
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  sessionAffinity: None
  type: ClusterIP
