apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tools
  name: tools
  namespace: test001
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 3600
    image: kylinsoong/busybox:1.28
    name: curl
    resources: {}
