apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    tags:
    - name: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APPLICATION_NAME}-binary
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      type: Binary
    strategy:
      sourceStrategy:
        forcePull: false
        from:
          kind: ImageStreamTag
          name: ${IMAGE_STREAM}
          namespace: ${IMAGE_STREAM_NAMESPACE}
      type: Source
parameters:
- displayName: Application name
  name: APPLICATION_NAME
  required: true
- displayName: image stream
  description: image stream of the builder image to build the application
  name: IMAGE_STREAM
  required: true
- displayName: image stream
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift