---

application_configmap: passenger-service

install_enmasse_truststore_secret: true
enmasse_truststore_secret: enmasse-truststore
enmasse_truststore: enmasse.jks

amqp_host: messaging.{{ project_enmasse }}.svc.cluster.local
amqp_port: 5671
amqp_query: transport.trustAll=false&transport.verifyHost=true
amqp_username: user
amqp_password: password
amqp_jms_pool_enabled: true
amqp_jms_pool_explicit_producer_cache_size: 10
amqp_jms_pool_use_anonymous_producers: true

spring_jms_pub_sub_domain: true
spring_jms_session_cache_size: 10
spring_jms_transacted: true
spring_jms_subscription_shared: true
spring_jms_subscription_durable: true
spring_jms_listener_concurrency: 10
spring_jms_listener_max_concurrency: 10

sender_destination_ride_requested: topic-ride-event
sender_destination_passenger_canceled: topic-passenger-event

listener_destination_driver_assigned: topic-driver-event
listener_subscription_driver_assigned: passenger-service

# thread pool size of the scheduler sending messages
scheduler_pool_size: 5
# min and max delay in seconds before sending a passenger cancelled event
scheduler_delay_min: 1
scheduler_delay_max: 3

ocp_application_template: "{{ resources_dir }}/passenger-service-template.yaml"
ocp_binary_build_config_template: "{{ resources_dir }}/passenger-service-binary.yaml"
ocp_pipeline_build_config_template: "{{ resources_dir }}/passenger-service-pipeline.yaml"
ocp_application_name: passenger-service
ocp_deployment_config: passenger-service
ocp_binary_build_config: "{{ ocp_application_name }}-binary"
ocp_pipeline_build_config: "{{ ocp_application_name }}-pipeline"
ocp_build_imagestream: redhat-openjdk18-openshift:1.4
git_url: "gogs:3000"
git_repository: "acme/passenger-service"