= DevOps
:toc: manual

== 概述

DevOps 是 `开发` 和 `运维` 这两个词的缩写。DevOps 是一套最佳实践方法论，旨在应用和服务的生命周期中促进 IT 专业人员（开发人员、运维人员和支持人员）之间的协作和交流，最终实现：

* 持续整合 - 从开发到运维和支持的轻松切换
* 持续部署 - 持续发布，或尽可能经常的发布
* 持续反馈 - 在应用和服务生命周期的各个阶段寻求来自利益相关方的反馈

DevOps 改变了员工的工作思维方式；DevOps 重视所作工作的多样性，支持企业为加快实现业务价值，而创建的主管流程，并评估社会和技术变革产生的影响。DevOps 能够让企业和个人建立和保持可持续工作实践的一种思维方式和工作方式。

成功的 DevOps:

* 能创造一个轻松的没有相互指责的企业文化环境，可以与他人分享自己的经验和场景，并产生共识，使人员和团队能够以持续有效的方式发挥他们的特长
* 为企业准时制生产策略(Just-in-Time JiT)提供应用和服务
* 通过基于风险的业务需求方案来确保 IT 服务的连续性
* 管理应用和服务的整个生命周期，包括生命周期的结束条件

== 企业 DevOps 的成功之路

.*术语表*
|===
|英语 |简称 |中文

|System of Engagement
|SoE
|交互型系统

|System of Record
|SoR
|记录型系统

|Bimodal challenge
|
|双峰挑战

|===

=== 企业体系的 DevOps

企业往往同时拥有交互型系统( SoE )和记录型系统(SoR)。SoE系统关注的是速度,SoR系统关注的是业务连续性。问题是当SoE频繁变更的时候,如何保障SoR的业务连续性呢?Gartner公司把这称为双峰挑战(Bimodal challenge)。

大多数企业的SoR的既有传统的系统与应用还需要维系和使用,使用DevOps建立准时制(just-in-time, JIT)概念的流水线过程可以帮到这类系统。

DevOps不能简单认为是一种工具、方法、技能或组织结构,DevOps的框架是结合所有这些元素来建立一个流水线的过程,使业务更快地运营,并能更快地应对变化。DevOps还可以通过戴明博士的计划(戴明环)来提升其成熟度。企业级的DevOps不仅仅是增强的敏捷开发和持续交付,同时也通过IT服务管理和应用程序管理来实现和促进业务增长并保障业务连续性。
