= OpenShift

Openshift 是一个容器云应用平台，以最少的配置和管理开销为开发人员和 IT 组织提供了一个安全的、资源可弹性扩展的云原生应用平台。

OpenShift 基于企业级 Linux，Docker 及 Kubernetes，提供了一个适用于当今企业级应用的，安全可扩展的多租户系统，同时也提供了厂商集成及第三方集成的应用程序运行时环境和软件包模版。 OpenShift 可以给客户的数据中心提供可靠的，灵活的和可扩展的容器云平台 到，使客户能够简单搭建，构建一个具有高安全性，高隐私，高合规，高保障性，高标准的云平台。

应用容器化、云原生化已成为行业的标准。应用以容器化的方式运行，容器化的应用相当是单个操作系统内的隔离分区，基于 Linux kernel 之上的轻量级虚拟化。容器提供了许多与虚拟机类似的优点，例如安全性，存储，安全性，网络隔离等，但同时需要更少的硬件资源和更快的启动和终止时间。使用 OpenShift 容器云有助于提高平台及平台之上的应用的效率，弹性和可移植性等。

== OpenShift 特性

* *自助服务* - OpenShift 集成了来自红帽自己、独立软件开发商、社区等多种成熟的解决方案介质和模版，例如：红帽 JBoss 中间件，Spring(Spring MVC, Spring Boot，Spring Cloud)，Mysql, MongoDB, Redis 等。基于这些介质和模版允许开发人员快速创建应用。OpenShift 还提供了开发者从源代码管理仓库开始使用和 S2I 构建应用程序。系统理员或运维人员可以为用户和项目定义资源配额和限制来系统资源控制的使用。

* *多语言的支持* - OpenShift 支持来自厂商的 Java，Node.js，PHP，Perl 和 Ruby 等。还有来自合作伙伴和更大的 Docker 社区的其他产品，MySQL，PostgreSQL，MongoDB数据库等。还支持轻量级中间件产品，如 Apache httpd，Apache Tomcat，JBoss EAP，ActiveMQ 和 Fuse 等。

== 常用命令

[cols="5a,2,2"]
|===
|Commands |Notes

|
----
oc login <URL> -u <USER> -p <PASSWORD>
----
|基本操作
|命令行远程登录

|
----
oc whoami
----
|基本操作
|查看当前用户

|
----
oc delete <RESOURCE_TYPE> name
----
|基本操作
|删除某类型资源

|
----
oc exec <POD> <COMMAND>
----
|基本操作
|在容器内执行命令

|
----
oc rsh <POD>
----
|基本操作
|进入容器内终端

|
----
oc get events -n <PROJECT>
----
|基本操作
|获取某 Project 关联的事件

|
----
oc logs -f <RESOURCE_TYPE>/<NAME>
----
|基本操作
|实时查看日志

|
----
oc rsync <pod>:<pod_dir> <local_dir> -c <container>
----
|基本操作
|向运行的容器拷贝东西

|
----
oc port-forward <pod> [<local_port>:]<remote_port>
----
|基本操作
|配置端口转发

|
----
oc adm policy who-can <verb> <resource>
----
|安全
|Indicates which users can perform an action on a resource

|
----
oc adm policy add-role-to-user <role> <username>
----
|安全
|Binds a given role to specified users

|
----
oc adm policy remove-role-from-user <role> <username>
----
|安全
|Removes a given role from specified users

|
----
oc adm policy remove-user <username>
----
|安全
|Removes specified users and all of their roles

|
----
oc adm policy add-role-to-group <role> <groupname>
----
|安全
|Binds a given role to specified groups

|
----
oc adm policy remove-role-from-group <role> <groupname>
----
|安全
|Removes a given role from specified groups

|
----
oc adm policy remove-group <groupname>
----
|安全
|Removes specified groups and all of their roles

|
----
oc adm policy add-cluster-role-to-user <role> <username>
----
|安全
|Binds a given role to specified users for all projects in the cluster

|
----
oc adm policy remove-cluster-role-from-user <role> <username>
----
|安全
|Removes a given role from specified users for all projects in the cluster

|
----
oc adm policy add-cluster-role-to-group role groupname
----
|安全
|Binds a given role to specified groups for all projects in the cluster

|
----
oc adm policy remove-cluster-role-from-group role groupname
----
|安全
|Removes a given role from specified groups for all projects in the cluster

|===
