---

- name: copy template for {{ jenkins_maven_slave_configmap }} configmap
  template:
    src: "{{ jenkins_maven_slave_configmap_template }}"
    dest: "{{ playbook_work_dir }}/jenkins-maven-slave.yaml"

- name: check if {{ jenkins_maven_slave_configmap }} configmap exists
  shell: "{{ openshift_cli }} get configmap {{ jenkins_maven_slave_configmap }} -n {{ ocp_project }}"
  register: jenkins_slave_configmap_exists
  ignore_errors: true
  changed_when: false

- name: create {{ jenkins_maven_slave_configmap }} configmap
  shell: "{{ openshift_cli }} create -f {{ playbook_work_dir }}/jenkins-maven-slave.yaml -n {{ ocp_project }}"
  when: jenkins_slave_configmap_exists is failed

- name: copy template for {{ jenkins_maven_slave_pvc }} pvc
  template:
    src: "{{ jenkins_maven_slave_pvc_template }}"
    dest: "{{ playbook_work_dir }}/{{ jenkins_maven_slave_pvc }}.yaml"

- name: check if {{ jenkins_maven_slave_pvc }} pvc exists
  shell: "{{ openshift_cli }} get pvc {{ jenkins_maven_slave_pvc }} -n {{ ocp_project }}"
  register: jenkins_slave_pvc_exists
  ignore_errors: true
  changed_when: false

- name: create {{ jenkins_maven_slave_pvc }} pvc
  shell: "{{ openshift_cli }} create -f {{ playbook_work_dir }}/{{ jenkins_maven_slave_pvc }}.yaml -n {{ ocp_project }}"
  when: jenkins_slave_pvc_exists is failed

# deploy jenkins
- name: check if jenkins is deployed
  shell: "{{ openshift_cli }} get dc {{ jenkins_service_name }} -n {{ ocp_project }}"
  register: jenkins_deployed
  ignore_errors: true
  changed_when: false

- name: deploy jenkins
  shell: |
    {{ openshift_cli }} process -f {{ jenkins_template }} \
    -p MEMORY_LIMIT=1Gi \
    | {{ openshift_cli }} create -f - -n {{ ocp_project }}
  when: jenkins_deployed is failed