apiVersion: v1
kind: Template
metadata:
  name: address
  app: enmasse
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${NAME}
      labels:
        type: address-config
        app: enmasse
    data:
      config.json: |-
        {
          "apiVersion": "enmasse.io/v1",
          "kind": "Address",
          "metadata": {
            "name": "${NAME}",
            "namespace": "${NAMESPACE}",
            "addressSpace": "${ADDRESS_SPACE}"
          },
          "spec": {
            "address": "${ADDRESS}",
            "type": "${TYPE}",
            "plan": "${PLAN}"
          }
        }
parameters:
  - name: NAME
    description: Name of configmap
    required: true
  - name: NAMESPACE
    description: namespace to deploy address to
    required: true
  - name: ADDRESS
    description: Address
    required: true
  - name: ADDRESS_SPACE
    description: Address space of address
    required: true
  - name: TYPE
    description: Type of address
    required: true
  - name: PLAN
    description: Plan to use for address
    required: true
